# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: yyqh01.reaper_yyqh
PackageVersion: "782.1"
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/yyqh01/reaper_yyqh_plugins/releases/download/Snapshot/reaper_yyqh.782.1.exe
  InstallerSha256: B7664A61DF8CC2933C5DB4A1BF645929C6734CC1BDBC3D0DE91499DA6A6A36AC
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-07-22
